# Generated by Django 3.2.6 on 2022-04-26 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0011_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('order_time', models.TimeField(auto_now=True)),
                ('order_status', models.CharField(max_length=50)),
                ('order_price', models.FloatField()),
                ('order_address', models.CharField(max_length=50)),
                ('order_city', models.CharField(max_length=50)),
                ('order_state', models.CharField(max_length=50)),
                ('order_zipcode', models.IntegerField()),
                ('order_phone', models.IntegerField()),
                ('order_email', models.EmailField(max_length=254)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
