# Generated by Django 3.2.6 on 2022-05-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('difficulty', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
            ],
        ),
    ]
