# Generated by Django 3.2.6 on 2022-06-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20220611_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2',
            field=models.CharField(default=1, max_length=100000),
            preserve_default=False,
        ),
    ]
